function GetMaxVals(currentSkin)
    local playerPed = PlayerPedId()

    local data = {
        sex = 1,
        face = 45,
        skin = 45,
        age_1 = GetNumHeadOverlayValues(3) - 1,
        age_2 = 10,
        beard_1 = GetNumHeadOverlayValues(1) - 1,
        beard_2 = 10,
        beard_3 = GetNumHairColors() - 1,
        beard_4 = GetNumHairColors() - 1,
        hair_1 = GetNumberOfPedDrawableVariations(playerPed, 2) - 1,
        hair_2 = GetNumberOfPedTextureVariations(playerPed, 2, currentSkin['hair_1'] or 0) - 1,
        hair_color_1 = GetNumHairColors() - 1,
        hair_color_2 = GetNumHairColors() - 1,
        eye_color = 31,
        eyebrows_1 = GetNumHeadOverlayValues(2) - 1,
        eyebrows_2 = 10,
        eyebrows_3 = GetNumHairColors() - 1,
        eyebrows_4 = GetNumHairColors() - 1,
        makeup_1 = GetNumHeadOverlayValues(4) - 1,
        makeup_2 = 10,
        makeup_3 = GetNumHairColors() - 1,
        makeup_4 = GetNumHairColors() - 1,
        lipstick_1 = GetNumHeadOverlayValues(8) - 1,
        lipstick_2 = 10,
        lipstick_3 = GetNumHairColors() - 1,
        lipstick_4 = GetNumHairColors() - 1,
        blemishes_1 = GetNumHeadOverlayValues(0) - 1,
        blemishes_2 = 10,
        blush_1 = GetNumHeadOverlayValues(5) - 1,
        blush_2 = 10,
        blush_3 = GetNumHairColors() - 1,
        complexion_1 = GetNumHeadOverlayValues(6) - 1,
        complexion_2 = 10,
        sun_1 = GetNumHeadOverlayValues(7) - 1,
        sun_2 = 10,
        moles_1 = GetNumHeadOverlayValues(9) - 1,
        moles_2 = 10,
        chest_1 = GetNumHeadOverlayValues(10) - 1,
        chest_2 = 10,
        chest_3 = GetNumHairColors() - 1,
        bodyb_1 = GetNumHeadOverlayValues(11) - 1,
        bodyb_2 = 10,
        ears_1 = GetNumberOfPedPropDrawableVariations(playerPed, 1) - 1,
        ears_2 = GetNumberOfPedPropTextureVariations(playerPed, 1, currentSkin['ears_1'] or 0 - 1),
        tshirt_1 = GetNumberOfPedDrawableVariations(playerPed, 8) - 1,
        tshirt_2 = GetNumberOfPedTextureVariations(playerPed, 8, currentSkin['tshirt_1'] or 0) - 1,
        torso_1 = GetNumberOfPedDrawableVariations(playerPed, 11) - 1,
        torso_2 = GetNumberOfPedTextureVariations(playerPed, 11, currentSkin['torso_1'] or 0) - 1,
        decals_1 = GetNumberOfPedDrawableVariations(playerPed, 10) - 1,
        decals_2 = GetNumberOfPedTextureVariations(playerPed, 10, currentSkin['decals_1'] or 0) - 1,
        arms = GetNumberOfPedDrawableVariations(playerPed, 3) - 1,
        arms_2 = 10,
        pants_1 = GetNumberOfPedDrawableVariations(playerPed, 4) - 1,
        pants_2 = GetNumberOfPedTextureVariations(playerPed, 4, currentSkin['pants_1'] or 0) - 1,
        shoes_1 = GetNumberOfPedDrawableVariations(playerPed, 6) - 1,
        shoes_2 = GetNumberOfPedTextureVariations(playerPed, 6, currentSkin['shoes_1'] or 0) - 1,
        mask_1 = GetNumberOfPedDrawableVariations(playerPed, 1) - 1,
        mask_2 = GetNumberOfPedTextureVariations(playerPed, 1, currentSkin['mask_1'] or 0) - 1,
        bproof_1 = GetNumberOfPedDrawableVariations(playerPed, 9) - 1,
        bproof_2 = GetNumberOfPedTextureVariations(playerPed, 9, currentSkin['bproof_1'] or 0) - 1,
        chain_1 = GetNumberOfPedDrawableVariations(playerPed, 7) - 1,
        chain_2 = GetNumberOfPedTextureVariations(playerPed, 7, currentSkin['chain_1'] or 0) - 1,
        bags_1 = GetNumberOfPedDrawableVariations(playerPed, 5) - 1,
        bags_2 = GetNumberOfPedTextureVariations(playerPed, 5, currentSkin['bags_1'] or 0) - 1,
        helmet_1 = GetNumberOfPedPropDrawableVariations(playerPed, 0) - 1,
        helmet_2 = GetNumberOfPedPropTextureVariations(playerPed, 0, currentSkin['helmet_1'] or 0) - 1,
        glasses_1 = GetNumberOfPedPropDrawableVariations(playerPed, 1) - 1,
        glasses_2 = GetNumberOfPedPropTextureVariations(playerPed, 1, currentSkin['glasses_1'] or 0 - 1),
        watches_1 = GetNumberOfPedPropDrawableVariations(playerPed, 6) - 1,
        watches_2 = GetNumberOfPedPropTextureVariations(playerPed, 6, currentSkin['watches_1'] or 0) - 1,
        bracelets_1 = GetNumberOfPedPropDrawableVariations(playerPed, 7) - 1,
        bracelets_2 = GetNumberOfPedPropTextureVariations(playerPed, 7, currentSkin['bracelets_1'] or 0 - 1),

        shapeSecond = 46,
        shapeMix = 10,
        skinSecond = 47,
        skinFirst = 47,
        skinMix = 10,
        shapeFirst = 47,

        --

        eyeBrownHigh = 3 * 10,
        eyeBrownForward = 2 * 10,
        eyesOpening = 3 * 10,

        noseWidth = 4 * 10,
        chinBoneLowering = 3 * 10,
        neckThickness = 2 * 10,

        noseBoneHigh = 2 * 10,
        chinBoneLenght = 3 * 10,
        lipsThickness = 2 * 10,

        nosePeakLowering = 2 * 10,
        nosePeakHigh = 2 * 10,
        jawBoneBackSize = 3 * 10,
        chinBoneSize = 2 * 10,
        cheeksWidth = 3 * 10,
        noseBoneTwist = 3 * 10,
        cheeksBoneWidth = 2 * 10,
        nosePeakSize = 2 * 10,
        cheeksBoneHigh = 2 * 10,

        chinHole = 2 * 10,
        jawBoneWidth = 2 * 10,


    }

    return data
end
