fx_version('bodacious')
game('gta5')

files {
	'data/**/carcols.meta',
	'data/**/carvariations.meta',
	'data/**/contentunlocks.meta',
	'data/**/handling.meta',
	'data/**/vehiclelayouts.meta',
	'data/**/vehicles.meta',
	'audioconfig/*.dat151.rel',
	'audioconfig/*.dat54.rel',
	'sfx/**/*.awc'
}

data_file 'CONTENT_UNLOCKING_META_FILE' 'data/**/contentunlocks.meta'
data_file 'HANDLING_FILE' 'data/**/handling.meta'
data_file 'VEHICLE_METADATA_FILE' 'data/**/vehicles.meta'
data_file 'CARCOLS_FILE' 'data/**/carcols.meta'
data_file 'VEHICLE_VARIATION_FILE' 'data/**/carvariations.meta'
data_file 'VEHICLE_LAYOUTS_FILE' 'data/**/vehiclelayouts.meta'

data_file "AUDIO_SYNTHDATA" "audioconfig/bmws1krreng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/bmws1krreng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/bmws1krreng_sounds.dat"
data_file 'AUDIO_GAMEDATA' 'audioconfig/m297zonda_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/m297zonda_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_m297zonda'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta011mit4g63_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta011mit4g63_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta011mit4g63'
data_file "AUDIO_SYNTHDATA" "audioconfig/lg14c6vette_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg14c6vette_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg14c6vette_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg14c6vette"
data_file "AUDIO_SYNTHDATA" "audioconfig/lg14c6vettena_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg14c6vettena_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg14c6vettena_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg14c6vettena"
data_file "AUDIO_SYNTHDATA" "audioconfig/lgcy02b16ff_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lgcy02b16ff_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lgcy02b16ff_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lgcy02b16ff"
data_file 'AUDIO_GAMEDATA' 'audioconfig/ta103ninjah2r_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ta103ninjah2r_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ta103ninjah2r'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s65b40_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s65b40_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s65b40'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/p60b40_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/p60b40_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/p60b40_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_p60b40'
data_file 'AUDIO_GAMEDATA' 'audioconfig/m158huayra_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/m158huayra_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_m158huayra'
data_file 'AUDIO_GAMEDATA' 'audioconfig/taaud40v8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/taaud40v8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_taaud40v8'
data_file "AUDIO_SYNTHDATA" "audioconfig/audirs4milltekeng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/audirs4milltekeng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/audirs4milltekeng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_audirs4milltekeng"
data_file 'AUDIO_GAMEDATA' 'audioconfig/aston59v12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aston59v12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aston59v12'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s63b44_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s63b44_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s63b44'
data_file 'AUDIO_GAMEDATA' 'audioconfig/m5cracklemod_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/m5cracklemod_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_m5cracklemod'
data_file "AUDIO_SYNTHDATA" "audioconfig/lg18bmwm4_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg18bmwm4_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg18bmwm4_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg18bmwm4"
data_file "AUDIO_SYNTHDATA" "audioconfig/szkgsxryoshimuraeng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/szkgsxryoshimuraeng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/szkgsxryoshimuraeng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_szkgsxryoshimuraeng"
data_file 'AUDIO_GAMEDATA' 'audioconfig/v6audiea839_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/v6audiea839_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_v6audiea839'
data_file "AUDIO_SYNTHDATA" "audioconfig/lg30meramgtr_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/lg30meramgtr_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/lg30meramgtr_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_lg30meramgtr"
data_file 'AUDIO_GAMEDATA' 'audioconfig/rb26dett_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/rb26dett_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_rb26dett'
data_file "AUDIO_SYNTHDATA" "audioconfig/mbnzc63eng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/mbnzc63eng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/mbnzc63eng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_mbnzc63eng"
data_file 'AUDIO_SYNTHDATA' 'audioconfig/mcp1eng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/mcp1eng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/mcp1eng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_mcp1eng'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/bgw16_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/bgw16_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/bgw16_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_bgw16'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lfasound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lfasound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lfasound'
data_file "AUDIO_SYNTHDATA" "audioconfig/evorllyeng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/evorllyeng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/evorllyeng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_evorllyeng"
data_file 'AUDIO_SYNTHDATA' 'audioconfig/tjz1eng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/tjz1eng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/tjz1eng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_tjz1eng'
data_file "AUDIO_SYNTHDATA" "audioconfig/z33dkffeng_amp.dat"
data_file "AUDIO_GAMEDATA" "audioconfig/z33dkffeng_game.dat"
data_file "AUDIO_SOUNDDATA" "audioconfig/z33dkffeng_sounds.dat"
data_file "AUDIO_WAVEPACK" "sfx/dlc_z33dkffeng"
data_file 'AUDIO_SYNTHDATA' 'audioconfig/918spyeng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/918spyeng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/918spyeng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_918spyeng'
data_file 'AUDIO_GAMEDATA' 'audioconfig/one1_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/one1_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_one1'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ferrarif140fe_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ferrarif140fe_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ferrarif140fe'
data_file "AUDIO_WAVEPACK" "sfx/dlc_bmws1krreng"
data_file 'AUDIO_SYNTHDATA' 'audioconfig/bnr34ffeng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/bnr34ffeng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/bnr34ffeng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_bnr34ffeng'
data_file 'AUDIO_GAMEDATA' 'audioconfig/porsche57v10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/porsche57v10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_porsche57v10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/cammedcharger_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/cammedcharger_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_cammedcharger'
data_file 'AUDIO_GAMEDATA' 'audioconfig/topfuelv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/topfuelv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_topfuelv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ktm1290r_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ktm1290r_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ktm1290r'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aq2jzgterace_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aq2jzgterace_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aq2jzgterace'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aqtoy2jzstock_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aqtoy2jzstock_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aqtoy2jzstock'
data_file 'AUDIO_GAMEDATA' 'audioconfig/n55b30t0_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/n55b30t0_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_n55b30t0'
data_file 'AUDIO_GAMEDATA' 'audioconfig/s55b30_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/s55b30_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_s55b30'
data_file 'AUDIO_GAMEDATA' 'audioconfig/dodgehemihellcat_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/dodgehemihellcat_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_dodgehemihellcat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/demonv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/demonv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_demonv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/tayamahar1_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/tayamahar1_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_tayamahar1'
data_file 'AUDIO_GAMEDATA' 'audioconfig/aqm275amg_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/aqm275amg_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_aqm275amg'
data_file 'AUDIO_GAMEDATA' 'audioconfig/suzukigsxr1k_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/suzukigsxr1k_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_suzukigsxr1k'
data_file 'AUDIO_GAMEDATA' 'audioconfig/lambov10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/lambov10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lambov10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/tagt3flat6_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/tagt3flat6_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_tagt3flat6'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ea888_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ea888_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ea888'
data_file 'AUDIO_GAMEDATA' 'audioconfig/rotary7_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/rotary7_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_rotary7'
data_file 'AUDIO_GAMEDATA' 'audioconfig/k20a_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/k20a_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_k20a'
data_file 'AUDIO_GAMEDATA' 'audioconfig/k20c_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/k20c_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_k20c'
data_file 'AUDIO_GAMEDATA' 'audioconfig/nfsv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/nfsv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_nfsv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/subaruej20_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/subaruej20_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_subaruej20'
data_file 'AUDIO_SYNTHDATA' 'audioconfig/wrxrllyeng_amp.dat'
data_file 'AUDIO_GAMEDATA' 'audioconfig/wrxrllyeng_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/wrxrllyeng_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_wrxrllyeng'
data_file 'AUDIO_GAMEDATA' 'audioconfig/r35sound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/r35sound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_r35sound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/488sound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/488sound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_488sound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/apollosv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/apollosv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_apollosv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/avesvv12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/avesvv12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_avesvv12'
data_file 'AUDIO_GAMEDATA' 'audioconfig/c6v8sound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/c6v8sound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_c6v8sound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/diablov12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/diablov12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_diablov12'
data_file 'AUDIO_GAMEDATA' 'audioconfig/f40v8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f40v8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f40v8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/f50v12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/f50v12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_f50v12'
data_file 'AUDIO_GAMEDATA' 'audioconfig/ferrarif12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/ferrarif12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_ferrarif12'
data_file 'AUDIO_GAMEDATA' 'audioconfig/gtaspanov10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/gtaspanov10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_gtaspanov10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/laferrarisound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/laferrarisound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_laferrarisound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/mclarenv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/mclarenv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_mclarenv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/murciev12_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/murciev12_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_murciev12'
data_file 'AUDIO_GAMEDATA' 'audioconfig/perfov10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/perfov10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_perfov10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/sestov10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/sestov10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_sestov10'
data_file 'AUDIO_GAMEDATA' 'audioconfig/urusv8_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/urusv8_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_urusv8'
data_file 'AUDIO_GAMEDATA' 'audioconfig/veyronsound_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/veyronsound_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_veyronsound'
data_file 'AUDIO_GAMEDATA' 'audioconfig/viperv10_game.dat'
data_file 'AUDIO_SOUNDDATA' 'audioconfig/viperv10_sounds.dat'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_viperv10'
data_file 'AUDIO_WAVEPACK' 'sfx/dlc_lgcy12ferf40'
