--░██████╗██╗░░██╗░█████╗░██████╗░░██████╗
--██╔════╝██║░░██║██╔══██╗██╔══██╗██╔════╝
--╚█████╗░███████║██║░░██║██████╔╝╚█████╗░
--░╚═══██╗██╔══██║██║░░██║██╔═══╝░░╚═══██╗
--██████╔╝██║░░██║╚█████╔╝██║░░░░░██████╔╝
--╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░░░░╚═════╝░

Config.WeaponLicense = 'license' -- Select between 'item' (qs-licenses) or 'license' (esx_license) system
Config.esx_licensecheckLicense = "esx_license:checkLicense"

Config.Shops = {
    ['Loja'] = {
        label = "Loja",
        coords = {
            vector3(26.3480, -1347.2395, 29.4970 - 0.95),
            vector3(374.4016, 325.7834, 103.5663 - 0.95),
            vector3(2557.1995, 382.7804, 108.6228 - 0.95),
            vector3(-3039.6729, 586.1946, 7.9089 - 0.95),
            vector3(-3242.3672, 1001.8326, 12.8307 - 0.95),
            vector3(547.2102, 2671.1279, 42.1564 - 0.95),
            vector3(1961.6765, 3740.8499, 32.3437 - 0.95),
            vector3(2678.9744, 3281.0415, 55.2411 - 0.95),
            vector3(1729.563, 6414.126, 35.037 - 0.95),
            vector3(-48.519, -1757.514, 29.421 - 0.95),
            vector3(1163.373, -323.801, 69.205 - 0.95),
            vector3(-707.501, -914.260, 19.215 - 0.95),
            vector3(-1820.523, 792.518, 138.118 - 0.95),
            vector3(1698.388, 4924.404, 42.063 - 0.95),
            vector3(1135.808, -982.281, 46.415 - 0.95),
            vector3(-1487.553, -379.107, 40.163 - 0.95),
            vector3(-2968.243, 390.910, 15.043 - 0.95),
            vector3(1166.024, 2708.930, 38.157 - 0.95),
            vector3(1392.562, 3604.684, 34.980 - 0.95),
        },
        Shop = {
            items = {
                [1] = {
                    name = "bread",
                    label = 'Pão',
                    price = 250,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 1,
                },
                [2] = {
                    name = "burger",
                    label = 'Hamburguer',
                    price = 250,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 2,
                },
                [3] = {
                    name = "taco",
                    label = 'Taco',
                    price = 250,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 3,
                },
                [4] = {
                    name = "donut",
                    label = 'Donut',
                    price = 250,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 4,
                },
                [5] = {
                    name = "icetea",
                    label = 'Ice Tea',
                    price = 250,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 5,
                },
                [6] = {
                    name = "tea",
                    label = 'Chá',
                    price = 250,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 6,
                },
                [7] = {
                    name = "monster",
                    label = 'Monster',
                    price = 250,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 7,
                },
                [8] = {
                    name = "orangejuice",
                    label = 'Sumo de Laranja',
                    price = 250,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 8,
                },
                [9] = {
                    name = "lemonade",
                    label = 'Limonada',
                    price = 250,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 9,
                },
                [10] = {
                    name = "milk",
                    label = 'Leite',
                    price = 250,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 10,
                },
                [11] = {
                    name = "chocolate",
                    label = 'Chocolate',
                    price = 250,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 11,
                },
                [12] = {
                    name = "cocacola",
                    label = 'Coca-cola',
                    price = 250,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 12,
                },
                [13] = {
                    name = "sprite",
                    label = 'Sprite',
                    price = 250,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 13,
                },
                [14] = {
                    name = "sashimi",
                    label = 'Sashimi',
                    price = 250,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 14,
                },
                [15] = {
                    name = "sushi",
                    label = 'Sushi',
                    price = 250,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 15,
                },
                [16] = {
                    name = "takoyaki",
                    label = 'Takoyaki',
                    price = 250,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 16,
                },
                [17] = {
                    name = "ramen",
                    label = 'Ramen',
                    price = 250,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 17,
                },
                [18] = {
                    name = "chips",
                    label = 'Batatas fritas',
                    price = 250,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 18,
                },
            },
            markerType = 27,
            markerSize = vector3(0.5, 0.5, 0.5),
            markerColour = { r = 255, g = 255, b = 255 },
            use3dtext = true,
            type = 'bank',                                                --'black_money', 'money' or 'bank'.
            msg = '[E] - Loja',
            blip = { id = 59, scale = 0.6, color = 2, title = 'Market' }, --or false,
            job = { 'all' },
            grade = { 'all' },
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'You dont have the license',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
    ['Ammunation'] = {
        label = "Ammunation",
        coords = {
            vector3(-660.9383, -938.4828, 21.8293 - 0.95),
            vector3(814.8696, -2153.4824, 29.6192 - 0.95),
            vector3(1696.9031, 3756.0020, 34.7053 - 0.95),
            vector3(-327.2197, 6079.8149, 31.4548 - 0.95),
            vector3(247.1145, -49.5405, 69.9411 - 0.95),
            vector3(17.5787, -1109.5398, 29.7972 - 0.95),
            vector3(2566.5327, 299.1978, 108.7349 - 0.95),
            vector3(-1113.5916, 2695.7588, 18.5543 - 0.95),
            vector3(842.9237, -1028.4463, 28.1948 - 0.95),
            vector3(-1310.7195, -392.4109, 36.6958 - 0.95),
        },
        Shop = {
            items = {
                [1] = {
                    name = "weapon_knife",
                    label = "faca",
                    price = 100,
                    amount = 100,
                    info = {},
                    type = "weapon",
                    slot = 1,
                },
                [2] = {
                    name = "weapon_bat",
                    label = "Taco de baseball",
                    price = 200,
                    amount = 100,
                    info = {},
                    type = "weapon",
                    slot = 2,
                },
                [3] = {
                    name = "weapon_snspistol",
                    label = "Pistola sns",
                    price = 1500,
                    amount = 100,
                    info = {},
                    type = "weapon",
                    slot = 3,
                },

            },
            markerType = 2,
            markerSize = vector3(0.2, 0.2, 0.1),
            markerColour = { r = 71, g = 181, b = 255 },
            use3dtext = true,
            type = 'money',                                                     --'black_money', 'money' or 'bank'.
            msg = '[E] - Ammunation',
            blip = { id = 110, scale = 0.8, color = 26, title = 'Ammunation' }, --or false,
            job = { 'all' },
            grade = { 'all' },
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'You dont have the license',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
    ['Loja PSP'] = {
        label = "Loja PSP",
        coords = {
            vector3(485.5179, -995.4824, 29.71)
        },
        Shop = {
            items = {
                [1] = {
                    name = "weapon_pistol",
                    label = "Pistola",
                    price = 0,
                    amount = 100,
                    info = {
                        ammo = "80",
                        attachments = {
                            { component = "COMPONENT_AT_PI_SUPP_02",  label = "Suppressor" },
                            { component = "COMPONENT_PISTOL_CLIP_02", label = "Ex. Clip" },
                            { component = "COMPONENT_AT_PI_FLSH",     label = "Flashlight" },
                        }
                    },
                    type = "weapon",
                    slot = 1,
                },
                [2] = {
                    name = "weapon_stungun",
                    label = "Tazer",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "weapon",
                    slot = 2,
                },
                [3] = {
                    name = "weapon_nightstick",
                    label = "Cacetete",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "weapon",
                    slot = 3,
                },
                [4] = {
                    name = "handcuffs",
                    label = "Algemas",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 4,
                },
                [5] = {
                    name = "rifle_ammo",
                    label = "Munição de Rifle",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 5,
                },
                [6] = {
                    name = "pistol_ammo",
                    label = "Munição de Pistola",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 6,
                },
                [7] = {
                    name = "shotgun_ammo",
                    label = "Munição de Shotgun",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 7,
                },
                [8] = {
                    name = "smg_ammo",
                    label = "Munição de SMG",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 8,
                },
                [9] = {
                    name = "kevlar",
                    label = "Colete",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 9,
                },
                [10] = {
                    name = "bandage",
                    label = "Bandagem",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 10,
                },
                [11] = {
                    name = "handcuffs",
                    label = "Algemas",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 11,
                },
            },
            markerType = 27,
            markerSize = vector3(0.5, 0.5, 0.5),
            markerColour = { r = 255, g = 255, b = 255 },
            use3dtext = true,
            type = 'money', --'black_money', 'money' or 'bank'.
            msg = '[E] - Loja de Armas',
            blip = false,   --or {id = 521, scale = 0.5, color = 3, title = 'LSPD Weapons Market'},
            job = { 'police' },
            grade = { 'all' },
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'You dont have the license',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
    ['Loja PSP Direção'] = {
        label = "Loja PSP Direção",
        coords = {
            vector3(487.0765, -997.0787, 29.71)
        },
        Shop = {
            items = {
                [1] = {
                    name = "weapon_smg",
                    label = "SMG",
                    price = 0,
                    amount = 100,
                    info = {
                        ammo = "80",
                        attachments = {
                            { component = "COMPONENT_AT_PI_SUPP",  label = "Suppressor" },
                            { component = "COMPONENT_SMG_CLIP_03", label = "Ex. Clip" },
                            { component = "COMPONENT_AT_AR_FLSH",  label = "Flashlight" },
                        }
                    },
                    type = "weapon",
                    slot = 1,
                },
                [2] = {
                    name = "WEAPON_TACTICALRIFLE",
                    label = "Rifle de Assalto M4",
                    price = 0,
                    amount = 100,
                    info = {
                        ammo = "80",
                        attachments = {
                            { component = "COMPONENT_AT_AR_FLSH_REH",        label = "Flashlight" },
                            { component = "COMPONENT_AT_AR_SUPP_02",         label = "Suppressor" },
                            { component = "COMPONENT_TACTICALRIFLE_CLIP_02", label = "Ex. Clip" },
                            { component = "COMPONENT_AT_AR_AFGRIP",          label = "Grip" },
                        }
                    },
                    type = "weapon",
                    slot = 2,
                },
                [3] = {
                    name = "WEAPON_PUMPSHOTGUN_MK2",
                    label = "Pump Shotgun MK2",
                    price = 0,
                    amount = 100,
                    info = {
                        ammo = "80",
                        attachments = {
                            { component = "COMPONENT_AT_AR_FLSH",    label = "Flashlight" },
                            { component = "COMPONENT_AT_SR_SUPP_03", label = "Suppressor" },
                        }
                    },
                    type = "weapon",
                    slot = 3,
                },
                [4] = {
                    name = "WEAPON_MUSKET",
                    label = "Musquete",
                    price = 0,
                    amount = 100,
                    info = {
                        ammo = "80",
                        attachments = {}
                    },
                    type = "weapon",
                    slot = 4,
                },
                [5] = {
                    name = "shotgun_ammo",
                    label = "Munição de Shotgun",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 5,
                },
            },
            markerType = 27,
            markerSize = vector3(0.5, 0.5, 0.5),
            markerColour = { r = 255, g = 255, b = 255 },
            use3dtext = true,
            type = 'money', --'black_money', 'money' or 'bank'.
            msg = '[E] - Loja de Armas',
            blip = false,   --or {id = 521, scale = 0.5, color = 3, title = 'LSPD Weapons Market'},
            job = { 'police' },
            grade = { 7, 8, 9, 10, 11, 12, 13, 14 },
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'You dont have the license',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
    ['Loja INEM'] = {
        label = "Loja INEM",
        coords = {
            vector3(306.8331, -601.5819, 42.30)
        },
        Shop = {
            items = {
                [1] = {
                    name = "medikit",
                    label = "Kit de Primeiros Socorros",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 1,
                },
                [2] = {
                    name = "bandage",
                    label = "Bandagem",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 2,
                }
            },
            markerType = 27,
            markerSize = vector3(0.5, 0.5, 0.5),
            markerColour = { r = 255, g = 255, b = 255 },
            use3dtext = true,
            type = 'money', --'black_money', 'money' or 'bank'.
            msg = '[E] - Loja do INEM',
            blip = false,   --or {id = 521, scale = 0.5, color = 3, title = 'LSPD Weapons Market'},
            job = { 'ambulance' },
            grade = { 'all' },
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'You dont have the license',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
    ['YouTools'] = {
        label = "YouTools",
        coords = {
            vector3(2747.5520, 3472.8064, 55.6716 - 0.95)
        },
        Shop = {
            items = {
                [1] = {
                    name = "radio",
                    label = "Rádio",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 1,
                },
                [2] = {
                    name = "weapon_hatchet",
                    label = "Machado",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "weapon",
                    slot = 2,
                },
                [3] = {
                    name = "weapon_battleaxe",
                    label = "Picareta",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "weapon",
                    slot = 3,
                },
                [4] = {
                    name = "weapon_knife",
                    label = "Faca",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "weapon",
                    slot = 4,
                },
                [5] = {
                    name = "backpack",
                    label = 'Mochila',
                    price = 0,
                    amount = 100,
                    info = { bagid = 'ID-' .. math.random(111111, 999999) },
                    type = "item",
                    slot = 5,
                },
                [6] = {
                    name = "contract",
                    label = "Contrato",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 6,
                },
                [7] = {
                    name = "repairkit",
                    label = "Kit de Reparação",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 7,
                },
                [8] = {
                    name = "sponge",
                    label = "Esponja",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 8,
                },
                [9] = {
                    name = "classic_phone",
                    label = "Telemóvel Clássico",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 9,
                },
                [10] = {
                    name = "black_phone",
                    label = "Telemóvel Preto",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 10,
                },
                [11] = {
                    name = "blue_phone",
                    label = "Telemóvel Azul",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 11,
                },
                [12] = {
                    name = "gold_phone",
                    label = "Telemóvel Dourado",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 12,
                },
                [13] = {
                    name = "red_phone",
                    label = "Telemóvel Vermelho",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 13,
                },
                [14] = {
                    name = "green_phone",
                    label = "Telemóvel Verde",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 14,
                },
                [15] = {
                    name = "greenlight_phone",
                    label = "Telemóvel Verde Claro",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 15,
                },
                [16] = {
                    name = "pink_phone",
                    label = "Telemóvel Rosa",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 16,
                },
                [17] = {
                    name = "white_phone",
                    label = "Telemóvel Branco",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 17,
                },
                [18] = {
                    name = "pooch_bag",
                    label = "Saco de plástico",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 18,
                },
                [19] = {
                    name = "lockpick",
                    label = "Lockpick",
                    price = 0,
                    amount = 100,
                    info = {},
                    type = "item",
                    slot = 19,
                },
            },
            markerType = 27,
            markerSize = vector3(0.5, 0.5, 0.5),
            markerColour = { r = 255, g = 255, b = 255 },
            use3dtext = true,
            type = 'bank', --'black_money', 'money' or 'bank'.
            msg = '[E] - YouTools',
            blip = { id = 402, scale = 0.9, color = 17, title = 'YouTools' },
            job = { 'all' },
            grade = { 'all' },
            license = false, -- Require license or not (false or the name of the license)
            licenseError = 'You dont have the license',
            distanceMarker = 10.0,
            distanceText = 1.5,
        }
    },
}
