Citizen.CreateThread(function ()
	SetConvarServerInfo("Fundadores", "Gonçalo Costa & Mycry_1337")
	SetConvarServerInfo("Desenvolvedor", "SrD4rkOficial")
	SetConvarServerInfo("Discord", "https://discord.gg/bg2p3RbgGp")
end)